version: "3"
services:
  mysql:
    image: "mysql:5.7"
    networks:
      - hotel-net
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=hmdb    
  backend:
    build: backend
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/hmdb?useSSL=false
    networks:
      - hotel-net
    depends_on:
      - mysql
    restart: always
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    networks:
      - hotel-net
    links:
      - backend
    depends_on:
      - backend
networks:
  hotel-net: